version: '3.8'  # Ensure you're using version 3.8 or higher

services:
  ipv4-data-server:
    build:
      context: ./ipv4-data-server
      dockerfile: Dockerfile
      ssh:
        - default  # Corrected SSH mapping
    ports:
      - "8080:8080"
    environment:
      - DB_URL=mongodb+srv://hilbertDB:OnDRsURqwU2x3N1R@cluster0.nkx7yi1.mongodb.net/hilbertDB
   

  ipv4-data-explorer:
    build:
      context: ./ipv4-data-explorer
      dockerfile: Dockerfile
      ssh:
        - default  # Corrected SSH mapping
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://ipv4-data-server:8080
    depends_on:
      - ipv4-data-server
